apiVersion: v2
name: giropops-chart
description: Helm chart para da aplicacao giropopos com Deployments, Services

version: 0.1.0
appVersion: "1.0"

maintainers:
  - name: Fellipe Martins
    email: fellipm@gmail.com

keywords:
  - ingress
  - giropops
  - redis

sources:
  - https://github.com/fellipe85/helm_senhas/

dependencies: []
