apiVersion: kyverno.io/v1
kind:ClusterPolicy
metadata:
  name: require-resourses-limits
spec:
  validationFailureAction: Enforce # aqui que vemos se será audit ou enforce
  rules:
  - name: validate-limits
    match: # ou usamos match ou exclude , depnde do que vamos fazer
      resources:
        kinds:
        - Pod
    validate: 
      message: "Precisa definir limites de recursos"
      pattern:  
        spec:
          containers:
          - name: "*"
            resources:
              limits:
                cpu:"?*"  #assim mostra que tem que existir um valor 
                memory: "?*"
