name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Get the commit hash
      id: vars
      run: echo "VERSION=$(cat ./melange-apko/version.txt )" >> $GITHUB_ENV

    - name: Build with Melange
      run: |
        mkdir ./app
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        #docker pull cgr.dev/chainguard/melange:latest
        #docker run --rm -v "${PWD}":/work cgr.dev/chainguard/melange keygen
        docker run --privileged --rm -v "$PWD":/work -w /work cgr.dev/chainguard/melange build ./melange-apko/giropops_alpine_melange.yaml --source-dir ./app --arch amd64,arm64 --signing-key ./melange-apko/melange.rsa

    - name: Build with Apko
      run: |
        ls -latr 
        ls -latr packages
        chown -R runner:docker packages
        docker run --rm --workdir /work -v $PWD:$PWD -w /work cgr.dev/chainguard/apko build melange-apko/giropops_alpine_apko.yaml giropops-senhas-melange:${{ env.VERSION }} giropops-senhas-melange.tar --arch host
        docker load << giropops-senhas-melange.tar 

    - name: Sign Docker image with Cosign
      run: |
        cosign sign --key ${{ secrets.COSIGN_KEY }} giropops-senhas-melange:${{ env.VERSION }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag giropops-senhas-melange:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/giropops-senhas-melange:${{ env.VERSION }}
        docker push ${{ secrets.DOCKER_USERNAME }}/giropops-senhas-melange:${{ env.VERSION }}
