name: Pipeline de build e deploy Giropops-Senhas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build with Melange
      run: |
        docker run --privileged --rm -v "${{ github.workspace }}":/work cgr.dev/chainguard/melange build giropops_alpine_melange.yaml --source-dir ./app --arch amd64,arm64 --signing-key melange.rsa

    - name: Build with Apko
      run: |
        docker run --rm --workdir /work -v ${{ github.workspace }}:${{ github.workspace }} -w "${{ github.workspace }}" cgr.dev/chainguard/apko build giropops_alpine_apko.yaml giropops-senhas-melange:1.0 giropops-senhas-melange.tar --arch host

    - name: Sign Docker image with Cosign
      run: |
        cosign sign --key ${{ secrets.COSIGN_KEY }} giropops-senhas-melange:1.0

    - name: Push Docker image to Docker Hub
      run: |
        docker tag giropops-senhas-melange:1.0 ${{ secrets.DOCKER_USERNAME }}/giropops-senhas-melange:1.0
        docker push ${{ secrets.DOCKER_USERNAME }}/giropops-senhas-melange:1.0
