name: Pipeline de build e deploy Giropops-Senhas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t my-image:latest .

    - name: Sign Docker image with Cosign
      run: |
        cosign sign --key ${{ secrets.COSIGN_KEY }} my-image:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker tag my-image:latest ${{ secrets.DOCKER_USERNAME }}/my-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
